### ISSUE TITLE
Label Highdriver4 -> pump connections

### ISSUE THREAD

**Issue by AydinGokce** [GeneralCybernetics/Ion-Concentration-Biomodulator#3]
Label these nets

![image](https://github.com/user-attachments/assets/d4a99a0e-a88e-4b57-a382-248350ae6f18)

**Comment by elijah0528** [comment]
<img width="498" alt="Screenshot 2024-08-12 at 6 14 10 PM" src="https://github.com/user-attachments/assets/904e51e6-9f84-4926-b8ab-d933514904c3">
Added labels
