### ISSUE TITLE
[LAYOUT]: Add keyed connectors for peltier cooler, co2 sensor, co2 solenoid, and 4x pinch solenoids

### ISSUE THREAD

**Issue by AydinGokce** [GeneralCybernetics/Ion-Concentration-Biomodulator#6]
for the co2 sensor connector, use the same as whatever they're using on the devboard. If you can't find it, use a 6-pin 1.25mm connector.

2-pin connector for peltier cooler:
- [socket](https://www.digikey.com/en/products/detail/w%C3%BCrth-elektronik/66200211122/4322246)
- [plug](https://www.digikey.com/en/products/detail/w%C3%BCrth-elektronik/662002013322/4322314)
- [contacts (20-24AWG)](https://www.digikey.com/en/products/detail/w%C3%BCrth-elektronik/66200213722DEC/4322491)

2-pin connector for co2 solenoid:
- [socket](https://www.digikey.com/en/products/detail/samtec-inc/IPL1-102-01-L-S-K/3728693)
- [plug](https://www.digikey.com/en/products/detail/samtec-inc/IPD1-02-S-K/3728692)
- [contacts (20-24AWG)](https://www.digikey.com/en/products/detail/samtec-inc/CC79L-2024-01-L/1120721)

8-pin connector for 4x pinch solenoids: 
- [socket](https://www.digikey.com/en/products/detail/samtec-inc/IPL1-104-01-L-D-K/2207634)
- [plug](https://www.digikey.com/en/products/detail/hirose-electric-co-ltd/DF11-8DS-2C/141255)
- [contacts (20-24AWG)](https://www.digikey.com/en/products/detail/samtec-inc/CC79L-2024-01-L/1120721)

**Comment by elijah0528** [comment]
Added all the sockets to the design

**Comment by elijah0528** [comment]
Crimp: https://www.digikey.com/en/products/detail/jst-sales-america-inc/SPH-002T-P0-5S/527359
Plug: https://www.digikey.com/en/products/detail/jst-sales-america-inc/PHR-4/608606
